### ISSUE TITLE
images should not be served by API backend. 

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Images#3]
lets discuss the possibilites yet with headless first approach

**Comment by pa-cholek** [comment]
I've already proposed the htaccess/redirect solution yesterday.

Let's say we have original file adress: https://awflms.etd24.pl/storage/course/7/blanditiis.jpg

### If we want to use browser cache for images, then:

- Frontend should try to load a file by using a link to file in form of either
  - Storage link (to the place where files after generation will really exist): https://awflms.etd24.pl/storage/course/7/blanditiis_760.jpg
  - Api link (with routing that matches everything after a fragment): https://awflms.etd24.pl/api/images/img/course/7/blanditiis_760.jpg
- We don't want to run laravel app if it is not neccessary, so we first try to find this file using htaccess
- In the storage link case, we have to do pattern matching on request uri if file doesn't exist, as we need to call api using link looking like this https://awflms.etd24.pl/api/images/img?path=course/7/blanditiis.jpg&w=760
- In Api link case we first use htaccess to check if file exist cutting the part after /img/ and checking for it in storage, and then if it doesn't exist we can parse `course/7/blanditiis_760.jpg` inside php as it will be passed as route param in request


### Alternatively, if we don't care about browser cache
We can do something like parsing the query in htaccess (so that we transform  https://awflms.etd24.pl/api/images/img?path=course/7/blanditiis.jpg&w=760 into https://awflms.etd24.pl/storage/course/7/blanditiis_760.jpg), checking if file exists and serving it, otherwise letting Laravel app handle this

There is an example of doing this with 'does not exist' check and rewriting rule to php when the file is not found
https://serverfault.com/questions/279981/htaccess-cant-check-dynamic-filepath-existence
But we probalby could do this with rewriting to file url if file is found and otherwise using normal laravel htaccess

**Comment by qunabu** [comment]
`htaccess` is apache only, 

this is fine for us, but that would require really sophisticated setup in order to launch the site

**Comment by qunabu** [comment]
my idea 

* lets assume backend and frontend share one hashing algorithm for params in url eg `${md5(image.orl + width)}.${image.extenstion}`
* frontend probes that url with `(new Image).src = cached_url` -
* if image throws 404 then `src` is replaced with api URL `http://{...}/image/resize?path=...&w=100` ->> this image is served by server 
* call above creates cached version of image in the `${md5(image.orl + width)}.${image.extenstion}` path 
* next call fetched image from cache
